### ISSUE TITLE
codespace does not start. problems in devcontainer ?

### ISSUE THREAD

**Issue by KrisThielemans** [PRDSI/PRDdefinition#1]
I cannot succeed in starting a new codespace. it always fails in the conda statement. Initially I had a problem when it was executing the miniconda install script that it said that `[[` wasn't known, so I've changed its execution to use `bash`. But since then it still doesn't succeed with somewhat cryptic errors.

Example log
[creation.log](https://github.com/PRDSI/PRDdefinition/files/10401341/creation.log)
this one seems a time-out.

**Comment by KrisThielemans** [comment]
Unfortunately I can currently not test this locally.

@johnstairs any ideas?

**Comment by johnstairs** [comment]
#2 should address the two problems here. 

One problem was that the default 2-core codespaces VM type did not have sufficient resources to build the previous devcontainer image. I think this is fixed now, but if you plan on using codespaces a lot, you could consider [prebuilding](https://docs.github.com/en/codespaces/prebuilding-your-codespaces) the codespace image.

**Comment by KrisThielemans** [comment]
it worked fine for me.
